import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, paddingHorizontal: 0 },
  titleContainer: { marginBottom: 10 },
  title: {
    color: '#000',
    textAlign: 'center',
    fontSize: 18,
    padding: 16,
    fontWeight: '500',
  },
  subTitle: {
    color: '#000',
    paddingBottom: 10,
    fontSize: 16,
    fontWeight: '500',
  },
  backContainer: {
    width: '10%',
    position: 'absolute',
    marginHorizontal: 10,
    marginTop: 10,
    zIndex: 2,
  },
  listContainer: { gap: 20, paddingBottom: 200 },
  deletedImage: {
    margin: 5,
    borderRadius: 16,
    height: 150,
    width: 150,
    backgroundColor: 'rgba(0,0,0,0.4)',
    position: 'absolute',
    zIndex: 99,
    justifyContent: 'center',
  },
  deletedItemText: { textAlign: 'center', color: 'white' },
  image: { height: 150, width: 150, borderRadius: 10},
  imageGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  imageContainer: {
    borderWidth: 1,
    padding: 20,
    borderRadius: 20,
    borderColor: 'rgba(0,0,0,0.3)',
    backgroundColor: '#f1f2f7',
  },
  emptyTitle: {
    textAlign: 'center',
    marginTop: 10,
    fontSize: 16,
    fontWeight: '600',
    color: 'red',
  },
  centerContainer: {
    flex: 1,
    color: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkbox: {
    position: 'absolute',
    right: 12,
    top: 12,
    zIndex: 1,
    backgroundColor: '#426bf2',
    padding: 4,
    borderRadius: 6,
  },
  addButton: {
    marginBottom: 20,
    borderRadius: 17,
    backgroundColor: '#426bf2',
    padding: 15,
    marginHorizontal: 20,
  },
  buttonText: { fontSize: 20, fontWeight: 'bold', color: 'white' },
  buttonContainer: { position: 'absolute', width: '100%', bottom: 0 },
  innerContainer: { paddingHorizontal: 20 },
  dateContainer: { alignSelf: 'center', marginTop: 10 },
});
