enum ROUTES {
  // ---- Stacks
  HOME_STACK = 'HOME_STACK',
  AUTH_STACK = 'AUTH_STACK',
  PROFILE_STACK = 'PROFILE_STACK',
  ADD_STACK = 'ADD_STACK',
  CLOTHING_STACK = 'CLOTHING_STACK',
  LOG_STACK = 'LOG_STACK',

  // ----- Auth Screens -----
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGN_UP_SCREEN = 'SIGN_UP_SCREEN',

  // ----- Logged-In Screens ------
  HOME_SCREEN = 'HOME_SCREEN',
  BROWSE_CLOTHING_SCREEN = 'BROWSE_CLOTHING_SCREEN',
  ADD_CLOTHING_SCREEN = 'ADD_CLOTHING_SCREEN',
  ADD_OUTFIT_SCREEN = 'ADD_OUTFIT_SCREEN',
  LOG_OUTFIT_SCREEN = 'LOG_OUTFIT_SCREEN',
  ADD_LOG_OUTFIT_SCREEN = 'ADD_LOG_OUTFIT_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  UPDATE_SCREEN = 'UPDATE_SCREEN',
  VIEW_CLOTHING_SCREEN = 'VIEW_CLOTHING_SCREEN',
}

export default ROUTES;
